version: '3'

volumes:
  # docker volume where Grafener data will be persisted (users, dashboards, ...)
  grafener_data:

services:

  grafener:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      # make ../tests folder available at /tmp/eplus_data.
      # datasources will use the later for source configuration (here /tmp/eplus_data/test_eplusout.csv.gz)
      - ../tests:/tmp/eplus_data
      # make datasource configuration automatic on container startup
      - ./provisioning:/etc/grafana/provisioning/datasources
      # persist all Grafener (Grafana) data across container restarts
      - grafener_data:/var/lib/grafana